### ISSUE TITLE
Mex link error

### ISSUE THREAD

**Issue by lildholdt** [brianrtaylor/cvos#1]
Hi

I was just trying your code on Ubuntu 14.04 and with VLFeat 0.9.20. However when I run mex_setup.m i get the following error:

Built solver.
/usr/bin/ld: cannot find -lvl
collect2: error: ld returned 1 exit status
    mex: link of ' "learn_bbox_gmm_mex.mexa64"' failed.

Unable to complete successfully. 

I am using g++ version 4.7 which is supported by Matlab.
Do you have any idea what could be wrong?

**Comment by brianrtaylor** [comment]
Hi

I think the problem might be because the compilation may not know where the vlfeat library is.

Starting in the base directory, try opening up, mex/mex_setup.m, looking for the VLFEAT_DIR variable, and setting it to the path to the vlfeat library. Let me know if this helps.

**Comment by lildholdt** [comment]
Hi

Thank you for your reply. The VLFEAT_DIR was set correctly however I hadn't compiled the library so the bin folder were missing. I guess it was too late in the evening ;)

Now I am able to complete the mex_setup succesfully, however when the demo start running I get the following error:

Undefined function or variable 'vec'.

Error in cross_bilateral_filter_step_test_fullimg (line 36)
ruvb = max(vec(uvb_rev_safe)) - min(vec(uvb_rev_safe));

Error in cvos_flow_occ (line 155)
  [uvb_cbf_, uvf_cbf_, occb_cbf_, occf_cbf_, occb_cbf_prob_, ...

Error in cvos (line 274)
  [uvb, uvb_cbf, uvf, uvf_cbf, uvb_rev, uvf_rev, ~, occb_cbf, ...

Error in cvos_run (line 114)
  cvos(sid{1}, PKG);

Error in demo (line 28)
cvos_run({'cars5'}, 'full');

Do you have an idea to what causes this?

**Comment by lildholdt** [comment]
Hi again

I managed to fix the previous error by adding the following file to the project: 
http://www.mathworks.com/matlabcentral/fileexchange/9061-risk-and-asset-allocation/content/AMeucciRiskandAssetAllocationRoutines/Ch9_OptimEstimationRisk/C_RobustAllocation/SeDuMi_1_1/vec.m

That got me further in the process. Currently, I am stuck at this:

```

C: solving the problem: 12.879
Post filtering (TV segmentation)
C: postfiltering: 2.650
C: setting up past for next frame: 0.020
Invalid MEX-file '/home/steffan/Desktop/cvos/mex/learn_bbox_gmm_mex.mexa64': libvl.so: cannot
open shared object file: No such file or directory

Error in cvos_update_box_models (line 38)
      [mu_fg, cov_fg, pi_fg, mu_bg, cov_bg, pi_bg] = learn_bbox_gmm_mex( ...

Error in cvos (line 638)
    boxes = cvos_update_box_models(boxes, layers, I1lab, Dx, Dy, params);

Error in cvos_run (line 114)
  cvos(sid{1}, PKG);

Error in demo (line 28)
cvos_run({'cars5'}, 'full');

```

Despite the location error of the file "learn_bbox_gmm_mex.mexa64" it actually does exist.

**Comment by brianrtaylor** [comment]
Hi

In matlab, navigate to the VLFEAT_DIR/toolbox directory and run the command vl_setup before running the demo (we will add this to the readme). On my machine, I found libvl.so in the MATLAB_ROOT/2012a/sys/os/glnxa64/libvl.so directory. Maybe also check to see that the .so file exists in your equivalent matlab directory.

Hope that helps!

**Comment by lildholdt** [comment]
I had run the vl_setup.m however the libvl.so was be missing from /MATLAB_ROOT/R2015a/sys/os/glnxa64. By copying the file to that location got me even further in the process.

A couple of files seems to be missing including flowToColor.m and computeColor.m however I found these in: https://github.com/bensapp/Stretchable-Models-for-Motion-Parsing/tree/master/thirdparty/mexOpticalFlow

Currently I am stuck at:

```
Undefined function or variable 'notick'.

Error in cvos_visual (line 103)
  imagesc(vis_weights_old); axt; notick;

```

I really appreciate your support and it seems that I am close to running the demo successfully :)

**Comment by lildholdt** [comment]
By deleting all instances of notick I was able to successfully run the demo.
Thanks again for your support and for sharing the code.

**Comment by vasiliykarasev** [comment]
Thanks! We added `notick.m`, `flowToColor.m`, `computeColor.m`, `vec.m` into the repository -- these were indeed missing.

**Comment by zhangjingling** [comment]
Error using mex
/home/zhangpei/Downloads/vlfeat-0.9.18/vl//generic.c: In function ‘char*
vl_configuration_to_string_copy()’:
/home/zhangpei/Downloads/vlfeat-0.9.18/vl//generic.c:900:47: error: invalid conversion from ‘void*’ to
‘char*’ [-fpermissive]
Error in mex_setup (line 43)
eval(cmd);

Error in run (line 63)
evalin('caller', [script ';']);

Error in mex_setup (line 35)
run('mex_setup');

I think i have correctly install vlfeat,and I have test the vlfeat 

> vl_version verbose
VLFeat version 0.9.18
    Static config: X64, little_endian, GNU C 40401 LP64, POSIX_threads, SSE2, OpenMP
    2 CPU(s): GenuineIntel MMX SSE SSE2 SSE3 SSE41
    OpenMP: max threads: 2 (library: 2)
    Debug: no
    SIMD enabled: yes


I donnot know why ?  need your help ,thank you

**Comment by vasiliykarasev** [comment]
Newer versions of gcc raised this warning to an error.
The simplest approach is probably to add the `-fpermissive` flag to `CFLAGS` and `CXXFLAGS` in this line: https://github.com/brianrtaylor/cvos/blob/master/mex/mex_setup.m#L35
For some reason, that line is also not linking vlfeat, although it should. I believe it should say:
`cmd = sprintf('mex -v learn_constraint_gmm_mex.cpp -L%s -lvl CFLAGS="-fpermissive -std=c99 -O -fPIC -DVL_DISABLE_SSE2 -DVL_DISABLE_AVX" CXXFLAGS="-fpermissive -O -fPIC " -I%s ', VLFEAT_LIB, VLFEAT_SRC);`

This works with gcc-5.4.0 on ubuntu 16.04. The `-fpermissive` flag is not required if you use gcc-4.9 (or older).
Please let us know if this works.

**Comment by fengenxiang1123** [comment]
Yes, " to add the -fpermissive flag to CFLAGS and CXXFLAGS" can solve the problem of invalid conversion.

**Comment by zaie** [comment]
Hi, adding flag -fpermissive solved the invalid conversion problem but a new problem comes out:
/tmp/mex_9020238538359264_20080/mathop.o: In function `vl_get_vector_comparison_function_f':
mathop.c:(.text+0xaa5): undefined reference to `_vl_distance_l2_avx_f'/tmp/mex_9020238538359264_20080/mathop.o: In function `vl_get_vector_3_comparison_function_f':
mathop.c:(.text+0xafe): undefined reference to `_vl_distance_mahalanobis_sq_avx_f'
/tmp/mex_9020238538359264_20080/mathop.o: In function `vl_get_vector_comparison_function_d':
mathop.c:(.text+0xdd5): undefined reference to `_vl_distance_l2_avx_d'
/tmp/mex_9020238538359264_20080/mathop.o: In function `vl_get_vector_3_comparison_function_d':
mathop.c:(.text+0xe2e): undefined reference to `_vl_distance_mahalanobis_sq_avx_d'
collect2: error: ld returned 1 exit status

I'm using matlab2014b, gcc 4.8, ubuntu14.04, vlfeat0.9.20. Maybe my matlab is too old. I don't know how to solve the problem. Please help me. Thank you.
